cicd added and dockerfile added

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -35,13 +35,18 @@ jobs:
       - name: Checkout Code
         uses: actions/checkout@v3
 
-      - name: Install Utilities
+      - name: Install AWS CLI if missing
         run: |
-          sudo apt-get update
-          sudo apt-get install -y jq unzip
+          if ! command -v aws &> /dev/null
+          then
+            echo "AWS CLI not found, installing..."
+            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+            unzip awscliv2.zip
+            sudo ./aws/install
+          fi
 
       - name: Configure AWS credentials
-        uses: aws-actions/configure-aws-credentials@v2
+        uses: aws-actions/configure-aws-credentials@v1
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
@@ -49,7 +54,7 @@ jobs:
 
       - name: Login to Amazon ECR
         id: login-ecr
-        uses: aws-actions/amazon-ecr-login@v1.7.1
+        uses: aws-actions/amazon-ecr-login@v1
         with:
           mask-password: true
 
@@ -73,7 +78,7 @@ jobs:
         uses: actions/checkout@v3
 
       - name: Configure AWS credentials
-        uses: aws-actions/configure-aws-credentials@v2
+        uses: aws-actions/configure-aws-credentials@v1
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
@@ -81,22 +86,11 @@ jobs:
 
       - name: Login to Amazon ECR
         id: login-ecr
-        uses: aws-actions/amazon-ecr-login@v1.7.1
-
-      - name: Print Docker version & login
-        run: |
-          docker --version
-          aws sts get-caller-identity
-
+        uses: aws-actions/amazon-ecr-login@v1
 
       - name: Pull latest image
         run: |
           docker pull ${{ needs.build-and-push-ecr-image.outputs.image }}
-
-      # Optional: Uncomment if you want to stop & remove existing container
-      # - name: Stop and remove container if running
-      #   run: |
-      #     docker ps -q --filter "name=texts" | grep -q . && docker stop texts && docker rm -fv texts
 
       - name: Run Docker Image to serve users
         run: |
@@ -107,5 +101,4 @@ jobs:
             ${{ needs.build-and-push-ecr-image.outputs.image }}
 
       - name: Clean previous images and containers
-        run: |
-          docker system prune -f
+        run: docker system prune -f
